language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t musammil/docker-frontend-ci-flow -f Dockerfile.dev .

script:
  - docker run -e CI=true USERNAME/docker-react npm run test